spring:
  application:
    name: bookme-mcp-server
  config:
    import: optional:file:.env[.properties]
#  main:
#    web-application-type: none
#    banner-mode: off
  ai:
    mcp:
      server:
        name: bookme-mcp-server
        version: 0.0.1
        enabled: true
        type: sync
server:
  port: 8081
#logging:
#  pattern:
#    console:
#  level:
#    root: off
book-me:
  url:
    bookme-backend-url: ${BOOKME_BACKEND_URL}
  auth:
    token: ${BOOKME_TOKEN}